-- CreateTable
CREATE TABLE `proprietarios` (
    `CPF_CNPJ` VARCHAR(191) NOT NULL,
    `RG` VARCHAR(191) NULL,
    `NOME` VARCHAR(191) NOT NULL,
    `FONE` VARCHAR(191) NOT NULL,
    `ENDERECO` VARCHAR(191) NULL,
    `BAIRRO` VARCHAR(191) NULL,
    `CIDADE` VARCHAR(191) NULL,
    `ESTADO` VARCHAR(191) NULL,

    PRIMARY KEY (`CPF_CNPJ`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `automoveis` (
    `PLACAS` VARCHAR(191) NOT NULL,
    `MODELO` VARCHAR(191) NOT NULL,
    `MARCA` VARCHAR(191) NOT NULL,
    `ANO` INTEGER NOT NULL,
    `COMBS` VARCHAR(191) NOT NULL,
    `COR` VARCHAR(191) NOT NULL,
    `CHASSI` VARCHAR(191) NOT NULL,
    `DATAENTRADA` DATETIME(3) NOT NULL,
    `HORAENTRADA` DATETIME(3) NOT NULL,
    `KMENTRADA` INTEGER NOT NULL,
    `VALORENTRADA` DECIMAL(10, 2) NOT NULL,
    `CPF_CNPJ` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`PLACAS`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `vendedor` (
    `CPF` VARCHAR(191) NOT NULL,
    `RG` VARCHAR(191) NOT NULL,
    `NOME` VARCHAR(191) NOT NULL,
    `ENDERECO` VARCHAR(191) NOT NULL,
    `BAIRRO` VARCHAR(191) NOT NULL,
    `CIDADE` VARCHAR(191) NOT NULL,
    `ESTADO` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`CPF`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `comprador` (
    `CPFCOMPR` VARCHAR(191) NOT NULL,
    `RG` VARCHAR(191) NOT NULL,
    `NOME` VARCHAR(191) NOT NULL,
    `ENDERECO` VARCHAR(191) NOT NULL,
    `CIDADE` VARCHAR(191) NOT NULL,
    `BAIRRO` VARCHAR(191) NOT NULL,
    `UF` VARCHAR(191) NOT NULL,
    `CEP` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`CPFCOMPR`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `venda` (
    `NUMVENDA` INTEGER NOT NULL AUTO_INCREMENT,
    `DATAVENDA` DATETIME(3) NOT NULL,
    `HORAVENDA` DATETIME(3) NOT NULL,
    `CPFVENDEDOR` VARCHAR(191) NOT NULL,
    `HORASAIDA` DATETIME(3) NULL,
    `DATASAIDA` DATETIME(3) NULL,
    `comprador_CPFCOMPR` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`NUMVENDA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `carros_vendidos` (
    `NUMVENDA` INTEGER NOT NULL,
    `PLACAS` VARCHAR(191) NOT NULL,
    `KMVENDA` INTEGER NOT NULL,
    `TIPOVENDA` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`PLACAS`, `NUMVENDA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tipos_gastos` (
    `COD` INTEGER NOT NULL AUTO_INCREMENT,
    `DESCRICAO` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`COD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `gastos_realizados` (
    `PLACAS` VARCHAR(191) NOT NULL,
    `CODTIPOGASTO` INTEGER NOT NULL,
    `VALORPAGO` DECIMAL(10, 2) NOT NULL,
    `DATA` DATETIME(3) NOT NULL,
    `tipos_gastos_COD` INTEGER NOT NULL,

    PRIMARY KEY (`PLACAS`, `CODTIPOGASTO`, `tipos_gastos_COD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `automoveis` ADD CONSTRAINT `automoveis_CPF_CNPJ_fkey` FOREIGN KEY (`CPF_CNPJ`) REFERENCES `proprietarios`(`CPF_CNPJ`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `venda` ADD CONSTRAINT `venda_CPFVENDEDOR_fkey` FOREIGN KEY (`CPFVENDEDOR`) REFERENCES `vendedor`(`CPF`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `venda` ADD CONSTRAINT `venda_comprador_CPFCOMPR_fkey` FOREIGN KEY (`comprador_CPFCOMPR`) REFERENCES `comprador`(`CPFCOMPR`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `carros_vendidos` ADD CONSTRAINT `carros_vendidos_NUMVENDA_fkey` FOREIGN KEY (`NUMVENDA`) REFERENCES `venda`(`NUMVENDA`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `carros_vendidos` ADD CONSTRAINT `carros_vendidos_PLACAS_fkey` FOREIGN KEY (`PLACAS`) REFERENCES `automoveis`(`PLACAS`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `gastos_realizados` ADD CONSTRAINT `gastos_realizados_PLACAS_fkey` FOREIGN KEY (`PLACAS`) REFERENCES `automoveis`(`PLACAS`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `gastos_realizados` ADD CONSTRAINT `gastos_realizados_tipos_gastos_COD_fkey` FOREIGN KEY (`tipos_gastos_COD`) REFERENCES `tipos_gastos`(`COD`) ON DELETE RESTRICT ON UPDATE CASCADE;
